export const ApplicationStatus = {
    APPLIED: 'APPLIED',
    HR_SCREEN: 'HR_SCREEN',
    TECHNICAL_INTERVIEW: 'TECHNICAL_INTERVIEW',
    FINAL_INTERVIEW: 'FINAL_INTERVIEW',
    OFFERED: 'OFFERED',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED',
    WITHDRAWN: 'WITHDRAWN',
};
